// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZoneSync.Core.Data;

#nullable disable

namespace ZoneSync.Core.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260707153628_AddCropPlanModule")]
    partial class AddCropPlanModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ZoneSync.Core.Entities.CheckRequirement", b =>
                {
                    b.Property<int>("CheckId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CheckId"));

                    b.Property<decimal>("CheckedValue")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("CropPlanId")
                        .HasColumnType("int");

                    b.Property<bool>("IsSatisfied")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastCheckDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NextCheckDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RequirementId")
                        .HasColumnType("int");

                    b.HasKey("CheckId");

                    b.HasIndex("CropPlanId");

                    b.HasIndex("RequirementId");

                    b.ToTable("CheckRequirements", (string)null);
                });

            modelBuilder.Entity("ZoneSync.Core.Entities.CropModule.Crop", b =>
                {
                    b.Property<int>("CropId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CropId"));

                    b.Property<string>("CropCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CropName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CropSeason")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IrrigationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CropId");

                    b.ToTable("Crops", (string)null);

                    b.HasData(
                        new
                        {
                            CropId = 1,
                            CropCategory = "Vegetable",
                            CropName = "Tomato",
                            CropSeason = "Summer",
                            IrrigationType = "Drip"
                        },
                        new
                        {
                            CropId = 2,
                            CropCategory = "Grain",
                            CropName = "Wheat",
                            CropSeason = "Winter",
                            IrrigationType = "Sprinkler"
                        });
                });

            modelBuilder.Entity("ZoneSync.Core.Entities.CropPlanModule.CropPlan", b =>
                {
                    b.Property<int>("CropPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CropPlanId"));

                    b.Property<DateTime?>("ActualHarvestTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("CropId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PlantingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PredictedHarvestTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ZoneId")
                        .HasColumnType("int");

                    b.HasKey("CropPlanId");

                    b.HasIndex("CropId");

                    b.HasIndex("ZoneId");

                    b.ToTable("CropPlans", (string)null);
                });

            modelBuilder.Entity("ZoneSync.Core.Entities.FarmZone.EntityActivityLog", b =>
                {
                    b.Property<int>("ActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActivityId"));

                    b.Property<DateTime>("ActionAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ActivityId");

                    b.HasIndex("UserId");

                    b.ToTable("EntityActivityLog", null, t =>
                        {
                            t.HasCheckConstraint("CHK_EntityActivityLog_ActionType", "[ActionType] IN ('Create', 'Update', 'Delete')");

                            t.HasCheckConstraint("CHK_EntityActivityLog_EntityType", "[EntityType] IN ('Zone', 'CropPlan', 'Task')");
                        });
                });

            modelBuilder.Entity("ZoneSync.Core.Entities.FarmZone.Farm", b =>
                {
                    b.Property<int>("FarmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FarmId"));

                    b.Property<string>("FarmLocation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FarmName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("NoOfZones")
                        .HasColumnType("int");

                    b.Property<int>("OwnerUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SoftDeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoilType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("TotalArea")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("FarmId");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("Farm", (string)null);
                });

            modelBuilder.Entity("ZoneSync.Core.Entities.FarmZone.Zone", b =>
                {
                    b.Property<int>("ZoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ZoneId"));

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("FarmId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SoftDeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SupervisorId")
                        .HasColumnType("int");

                    b.Property<decimal>("ZoneArea")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("ZoneName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ZoneStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ZoneId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("FarmId");

                    b.HasIndex("SupervisorId");

                    b.ToTable("Zone", null, t =>
                        {
                            t.HasCheckConstraint("CHK_Zone_Status", "[ZoneStatus] IN ('Available', 'Planted', 'Inactive')");
                        });
                });

            modelBuilder.Entity("ZoneSync.Core.Entities.FarmZone.ZoneUser", b =>
                {
                    b.Property<int>("ZoneId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ZoneId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ZoneUser", (string)null);
                });

            modelBuilder.Entity("ZoneSync.Core.Entities.GrowthStageModule.GrowthStage", b =>
                {
                    b.Property<int>("StageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StageId"));

                    b.Property<int>("CropId")
                        .HasColumnType("int");

                    b.Property<int>("StageDuration")
                        .HasColumnType("int");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StageOrder")
                        .HasColumnType("int");

                    b.HasKey("StageId");

                    b.HasIndex("CropId");

                    b.ToTable("GrowthStages", (string)null);

                    b.HasData(
                        new
                        {
                            StageId = 1,
                            CropId = 1,
                            StageDuration = 10,
                            StageName = "Germination",
                            StageOrder = 1
                        },
                        new
                        {
                            StageId = 2,
                            CropId = 1,
                            StageDuration = 30,
                            StageName = "Vegetative",
                            StageOrder = 2
                        },
                        new
                        {
                            StageId = 3,
                            CropId = 1,
                            StageDuration = 20,
                            StageName = "Harvest",
                            StageOrder = 3
                        },
                        new
                        {
                            StageId = 4,
                            CropId = 2,
                            StageDuration = 25,
                            StageName = "Tillering",
                            StageOrder = 1
                        });
                });

            modelBuilder.Entity("ZoneSync.Core.Entities.Identity.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("ZoneSync.Core.Entities.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasFilter("[PhoneNumber] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ZoneSync.Core.Entities.Identity.FarmMembership", b =>
                {
                    b.Property<int>("FarmId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("RoleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("FarmId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("FarmMembership", (string)null);
                });

            modelBuilder.Entity("ZoneSync.Core.Entities.Identity.Invitation", b =>
                {
                    b.Property<int>("InvitationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvitationId"));

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FarmId")
                        .HasColumnType("int");

                    b.Property<string>("InvitationName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("InvitationStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("InvitationToken")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("InvitedEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("InvitedPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("InvitedRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ReceivedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("SentByUserId")
                        .HasColumnType("int");

                    b.Property<string>("VerificationCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("InvitationId");

                    b.HasIndex("InvitationToken")
                        .IsUnique();

                    b.HasIndex("ReceivedByUserId");

                    b.HasIndex("SentByUserId");

                    b.ToTable("Invitation", (string)null);
                });

            modelBuilder.Entity("ZoneSync.Core.Entities.Identity.UserProfile", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("AspNetUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("SSN")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<DateTime?>("SoftDeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserFirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserLastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("AspNetUserId")
                        .IsUnique();

                    b.HasIndex("SSN")
                        .IsUnique()
                        .HasFilter("[SSN] IS NOT NULL");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("ZoneSync.Core.Entities.StageInformationModule.StageInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActualEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ActualStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CropPlanId")
                        .HasColumnType("int");

                    b.Property<string>("DelayDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("PredictedEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PredictedStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StageId")
                        .HasColumnType("int");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StageStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CropPlanId");

                    b.HasIndex("StageId");

                    b.ToTable("StageInformations", (string)null);
                });

            modelBuilder.Entity("ZoneSync.Core.Entities.StageRequirementModule.StageRequirement", b =>
                {
                    b.Property<int>("ReqId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReqId"));

                    b.Property<string>("ApplicablePeriod")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DefaultVerificationAfterHours")
                        .HasColumnType("int");

                    b.Property<bool>("IsChosenByUser")
                        .HasColumnType("bit");

                    b.Property<decimal>("MaxValue")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("MinValue")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("ReqName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StageId")
                        .HasColumnType("int");

                    b.HasKey("ReqId");

                    b.HasIndex("StageId");

                    b.ToTable("StageRequirements", (string)null);

                    b.HasData(
                        new
                        {
                            ReqId = 1,
                            ApplicablePeriod = "Daily",
                            DefaultVerificationAfterHours = 24,
                            IsChosenByUser = true,
                            MaxValue = 70m,
                            MinValue = 45m,
                            ReqName = "Soil moisture",
                            StageId = 1
                        },
                        new
                        {
                            ReqId = 2,
                            ApplicablePeriod = "Daily",
                            DefaultVerificationAfterHours = 24,
                            IsChosenByUser = true,
                            MaxValue = 30m,
                            MinValue = 18m,
                            ReqName = "Temperature",
                            StageId = 2
                        },
                        new
                        {
                            ReqId = 3,
                            ApplicablePeriod = "Weekly",
                            DefaultVerificationAfterHours = 48,
                            IsChosenByUser = true,
                            MaxValue = 60m,
                            MinValue = 30m,
                            ReqName = "Water level",
                            StageId = 4
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("ZoneSync.Core.Entities.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ZoneSync.Core.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ZoneSync.Core.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("ZoneSync.Core.Entities.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZoneSync.Core.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ZoneSync.Core.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ZoneSync.Core.Entities.CheckRequirement", b =>
                {
                    b.HasOne("ZoneSync.Core.Entities.CropPlanModule.CropPlan", "CropPlan")
                        .WithMany("CheckRequirements")
                        .HasForeignKey("CropPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ZoneSync.Core.Entities.StageRequirementModule.StageRequirement", "StageRequirement")
                        .WithMany()
                        .HasForeignKey("RequirementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CropPlan");

                    b.Navigation("StageRequirement");
                });

            modelBuilder.Entity("ZoneSync.Core.Entities.CropPlanModule.CropPlan", b =>
                {
                    b.HasOne("ZoneSync.Core.Entities.CropModule.Crop", "Crop")
                        .WithMany("CropPlans")
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ZoneSync.Core.Entities.FarmZone.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Crop");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("ZoneSync.Core.Entities.FarmZone.EntityActivityLog", b =>
                {
                    b.HasOne("ZoneSync.Core.Entities.Identity.UserProfile", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ZoneSync.Core.Entities.FarmZone.Farm", b =>
                {
                    b.HasOne("ZoneSync.Core.Entities.Identity.UserProfile", "OwnerUser")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("ZoneSync.Core.Entities.FarmZone.Zone", b =>
                {
                    b.HasOne("ZoneSync.Core.Entities.Identity.UserProfile", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ZoneSync.Core.Entities.FarmZone.Farm", "Farm")
                        .WithMany("Zones")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ZoneSync.Core.Entities.Identity.UserProfile", "Supervisor")
                        .WithMany()
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByUser");

                    b.Navigation("Farm");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("ZoneSync.Core.Entities.FarmZone.ZoneUser", b =>
                {
                    b.HasOne("ZoneSync.Core.Entities.Identity.UserProfile", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ZoneSync.Core.Entities.FarmZone.Zone", "Zone")
                        .WithMany("ZoneUsers")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("ZoneSync.Core.Entities.GrowthStageModule.GrowthStage", b =>
                {
                    b.HasOne("ZoneSync.Core.Entities.CropModule.Crop", "Crop")
                        .WithMany("GrowthStages")
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Crop");
                });

            modelBuilder.Entity("ZoneSync.Core.Entities.Identity.FarmMembership", b =>
                {
                    b.HasOne("ZoneSync.Core.Entities.Identity.UserProfile", "UserProfile")
                        .WithMany("FarmMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("ZoneSync.Core.Entities.Identity.Invitation", b =>
                {
                    b.HasOne("ZoneSync.Core.Entities.Identity.UserProfile", "ReceivedByUser")
                        .WithMany("ReceivedInvitations")
                        .HasForeignKey("ReceivedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ZoneSync.Core.Entities.Identity.UserProfile", "SentByUser")
                        .WithMany("SentInvitations")
                        .HasForeignKey("SentByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReceivedByUser");

                    b.Navigation("SentByUser");
                });

            modelBuilder.Entity("ZoneSync.Core.Entities.Identity.UserProfile", b =>
                {
                    b.HasOne("ZoneSync.Core.Entities.Identity.ApplicationUser", "ApplicationUser")
                        .WithOne()
                        .HasForeignKey("ZoneSync.Core.Entities.Identity.UserProfile", "AspNetUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("ZoneSync.Core.Entities.StageInformationModule.StageInformation", b =>
                {
                    b.HasOne("ZoneSync.Core.Entities.CropPlanModule.CropPlan", "CropPlan")
                        .WithMany("StageInformations")
                        .HasForeignKey("CropPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ZoneSync.Core.Entities.GrowthStageModule.GrowthStage", "GrowthStage")
                        .WithMany()
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CropPlan");

                    b.Navigation("GrowthStage");
                });

            modelBuilder.Entity("ZoneSync.Core.Entities.StageRequirementModule.StageRequirement", b =>
                {
                    b.HasOne("ZoneSync.Core.Entities.GrowthStageModule.GrowthStage", "GrowthStage")
                        .WithMany("StageRequirements")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GrowthStage");
                });

            modelBuilder.Entity("ZoneSync.Core.Entities.CropModule.Crop", b =>
                {
                    b.Navigation("CropPlans");

                    b.Navigation("GrowthStages");
                });

            modelBuilder.Entity("ZoneSync.Core.Entities.CropPlanModule.CropPlan", b =>
                {
                    b.Navigation("CheckRequirements");

                    b.Navigation("StageInformations");
                });

            modelBuilder.Entity("ZoneSync.Core.Entities.FarmZone.Farm", b =>
                {
                    b.Navigation("Zones");
                });

            modelBuilder.Entity("ZoneSync.Core.Entities.FarmZone.Zone", b =>
                {
                    b.Navigation("ZoneUsers");
                });

            modelBuilder.Entity("ZoneSync.Core.Entities.GrowthStageModule.GrowthStage", b =>
                {
                    b.Navigation("StageRequirements");
                });

            modelBuilder.Entity("ZoneSync.Core.Entities.Identity.UserProfile", b =>
                {
                    b.Navigation("FarmMemberships");

                    b.Navigation("ReceivedInvitations");

                    b.Navigation("SentInvitations");
                });
#pragma warning restore 612, 618
        }
    }
}
